name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Set up pnpm
      uses: pnpm/action-setup@v6

    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Lint
      run: pnpm run lint

    - name: Test
      run: pnpm run test

    - name: Build
      run: make dev

    - name: Deploy
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
        chmod 600 ssh_key.pem
        sshpass -Ppassphrase -p ${{ secrets.SSH_KEY_PASSPHRASE }} scp -i ssh_key.pem -o StrictHostKeyChecking=no -r build/* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/var/www/html/

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: prod

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Set up pnpm
      uses: pnpm/action-setup@v6

    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build
      run: make prod

    - name: Deploy
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
        chmod 600 ssh_key.pem
        sshpass -Ppassphrase -p ${{ secrets.SSH_KEY_PASSPHRASE }} scp -i ssh_key.pem -o StrictHostKeyChecking=no -r build/* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/var/www/html/
