name: Build and Deploy PROD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Node
      uses: actions/setup-node@v5
      with:
        node-version: 24

    - name: Install dependencies
      run: npm install

    - name: Build
      run: make prod
  
    - name: Depoly
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
        chmod 600 ssh_key.pem
        sshpass -Ppassphrase -p ${{ secrets.SSH_KEY_PASSPHRASE }} scp -i ssh_key.pem -o StrictHostKeyChecking=no -r build/* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/var/www/html/
